// config/countries.js
export const COUNTRY_CODES = {
  // Existing Middle East entries
  '+971': { country: 'UAE', currency: 'AED', symbol: 'د.إ', locale: 'ar-AE', flag: '🇦🇪' },
  '+966': { country: 'Saudi Arabia', currency: 'SAR', symbol: 'ر.س', locale: 'ar-SA', flag: '🇸🇦' },
  '+974': { country: 'Qatar', currency: 'QAR', symbol: 'ر.ق', locale: 'ar-QA', flag: '🇶🇦' },
  '+973': { country: 'Bahrain', currency: 'BHD', symbol: '.د.ب', locale: 'ar-BH', flag: '🇧🇭' },
  '+968': { country: 'Oman', currency: 'OMR', symbol: 'ر.ع.', locale: 'ar-OM', flag: '🇴🇲' },
  '+965': { country: 'Kuwait', currency: 'KWD', symbol: 'د.ك', locale: 'ar-KW', flag: '🇰🇼' },
  '+961': { country: 'Lebanon', currency: 'LBP', symbol: 'ل.ل.', locale: 'ar-LB', flag: '🇱🇧' },
  '+963': { country: 'Syria', currency: 'SYP', symbol: '£S', locale: 'ar-SY', flag: '🇸🇾' },
  '+962': { country: 'Jordan', currency: 'JOD', symbol: 'د.ا', locale: 'ar-JO', flag: '🇯🇴' },
  '+967': { country: 'Yemen', currency: 'YER', symbol: '﷼', locale: 'ar-YE', flag: '🇾🇪' },
  '+970': { country: 'Palestine', currency: 'ILS', symbol: '₪', locale: 'ar-PS', flag: '🇵🇸' },

  // North Africa (Existing + Additions)
  '+20': { country: 'Egypt', currency: 'EGP', symbol: 'ج.م', locale: 'ar-EG', flag: '🇪🇬' },
  '+218': { country: 'Libya', currency: 'LYD', symbol: 'ل.د', locale: 'ar-LY', flag: '🇱🇾' },
  '+216': { country: 'Tunisia', currency: 'TND', symbol: 'د.ت', locale: 'ar-TN', flag: '🇹🇳' },
  '+213': { country: 'Algeria', currency: 'DZD', symbol: 'د.ج', locale: 'ar-DZ', flag: '🇩🇿' },
  '+212': { country: 'Morocco', currency: 'MAD', symbol: 'د.م.', locale: 'ar-MA', flag: '🇲🇦' },
  '+249': { country: 'Sudan', currency: 'SDG', symbol: 'ج.س.', locale: 'ar-SD', flag: '🇸🇩' },

  // Europe (Existing + Additions)
  '+44': { country: 'United Kingdom', currency: 'GBP', symbol: '£', locale: 'en-GB', flag: '🇬🇧' },
  '+33': { country: 'France', currency: 'EUR', symbol: '€', locale: 'fr-FR', flag: '🇫🇷' },
  '+49': { country: 'Germany', currency: 'EUR', symbol: '€', locale: 'de-DE', flag: '🇩🇪' },
  '+39': { country: 'Italy', currency: 'EUR', symbol: '€', locale: 'it-IT', flag: '🇮🇹' },
  '+34': { country: 'Spain', currency: 'EUR', symbol: '€', locale: 'es-ES', flag: '🇪🇸' },
  '+351': { country: 'Portugal', currency: 'EUR', symbol: '€', locale: 'pt-PT', flag: '🇵🇹' },
  '+31': { country: 'Netherlands', currency: 'EUR', symbol: '€', locale: 'nl-NL', flag: '🇳🇱' },
  '+32': { country: 'Belgium', currency: 'EUR', symbol: '€', locale: 'nl-BE', flag: '🇧🇪' },
  '+41': { country: 'Switzerland', currency: 'CHF', symbol: 'Fr.', locale: 'de-CH', flag: '🇨🇭' },
  '+43': { country: 'Austria', currency: 'EUR', symbol: '€', locale: 'de-AT', flag: '🇦🇹' },
  '+46': { country: 'Sweden', currency: 'SEK', symbol: 'kr', locale: 'sv-SE', flag: '🇸🇪' },
  '+47': { country: 'Norway', currency: 'NOK', symbol: 'kr', locale: 'nb-NO', flag: '🇳🇴' },
  '+45': { country: 'Denmark', currency: 'DKK', symbol: 'kr', locale: 'da-DK', flag: '🇩🇰' },
  '+358': { country: 'Finland', currency: 'EUR', symbol: '€', locale: 'fi-FI', flag: '🇫🇮' },
  '+353': { country: 'Ireland', currency: 'EUR', symbol: '€', locale: 'en-IE', flag: '🇮🇪' },
  '+48': { country: 'Poland', currency: 'PLN', symbol: 'zł', locale: 'pl-PL', flag: '🇵🇱' },
  '+380': { country: 'Ukraine', currency: 'UAH', symbol: '₴', locale: 'uk-UA', flag: '🇺🇦' },
  '+40': { country: 'Romania', currency: 'RON', symbol: 'lei', locale: 'ro-RO', flag: '🇷🇴' },
  '+30': { country: 'Greece', currency: 'EUR', symbol: '€', locale: 'el-GR', flag: '🇬🇷' },
  '+36': { country: 'Hungary', currency: 'HUF', symbol: 'Ft', locale: 'hu-HU', flag: '🇭🇺' },
  '+420': { country: 'Czech Republic', currency: 'CZK', symbol: 'Kč', locale: 'cs-CZ', flag: '🇨🇿' },
  '+421': { country: 'Slovakia', currency: 'EUR', symbol: '€', locale: 'sk-SK', flag: '🇸🇰' },
  '+386': { country: 'Slovenia', currency: 'EUR', symbol: '€', locale: 'sl-SI', flag: '🇸🇮' },
  '+385': { country: 'Croatia', currency: 'EUR', symbol: '€', locale: 'hr-HR', flag: '🇭🇷' },
  '+381': { country: 'Serbia', currency: 'RSD', symbol: 'дин.', locale: 'sr-RS', flag: '🇷🇸' },
   '+355': { country: 'Albania', currency: 'ALL', symbol: 'L', locale: 'sq-AL', flag: '🇦🇱' },
  '+376': { country: 'Andorra', currency: 'EUR', symbol: '€', locale: 'ca-AD', flag: '🇦🇩' },
  '+375': { country: 'Belarus', currency: 'BYN', symbol: 'Br', locale: 'be-BY', flag: '🇧🇾' },
  '+387': { country: 'Bosnia and Herzegovina', currency: 'BAM', symbol: 'KM', locale: 'bs-BA', flag: '🇧🇦' },
  '+372': { country: 'Estonia', currency: 'EUR', symbol: '€', locale: 'et-EE', flag: '🇪🇪' },
  '+354': { country: 'Iceland', currency: 'ISK', symbol: 'kr', locale: 'is-IS', flag: '🇮🇸' },
  '+371': { country: 'Latvia', currency: 'EUR', symbol: '€', locale: 'lv-LV', flag: '🇱🇻' },
  '+423': { country: 'Liechtenstein', currency: 'CHF', symbol: 'CHF', locale: 'de-LI', flag: '🇱🇮' },
  '+370': { country: 'Lithuania', currency: 'EUR', symbol: '€', locale: 'lt-LT', flag: '🇱🇹' },
  '+352': { country: 'Luxembourg', currency: 'EUR', symbol: '€', locale: 'fr-LU', flag: '🇱🇺' },
  '+356': { country: 'Malta', currency: 'EUR', symbol: '€', locale: 'mt-MT', flag: '🇲🇹' },
  '+373': { country: 'Moldova', currency: 'MDL', symbol: 'L', locale: 'ro-MD', flag: '🇲🇩' },
  '+377': { country: 'Monaco', currency: 'EUR', symbol: '€', locale: 'fr-MC', flag: '🇲🇨' },
  '+382': { country: 'Montenegro', currency: 'EUR', symbol: '€', locale: 'sr-ME', flag: '🇲🇪' },
  '+389': { country: 'North Macedonia', currency: 'MKD', symbol: 'ден', locale: 'mk-MK', flag: '🇲🇰' },
  '+378': { country: 'San Marino', currency: 'EUR', symbol: '€', locale: 'it-SM', flag: '🇸🇲' },
  '+379': { country: 'Vatican City', currency: 'EUR', symbol: '€', locale: 'it-VA', flag: '🇻🇦' },
  '+359': { country: 'Bulgaria', currency: 'BGN', symbol: 'лв', locale: 'bg-BG', flag: '🇧🇬' },
  
  // North America
  '+1': { country: 'United States', currency: 'USD', symbol: '$', locale: 'en-US', flag: '🇺🇸' },
  '+1C': { country: 'Canada', currency: 'CAD', symbol: 'C$', locale: 'en-CA', flag: '🇨🇦' },
  
  // Asia (Complete)
  '+93': { country: 'Afghanistan', currency: 'AFN', symbol: '؋', locale: 'ps-AF', flag: '🇦🇫' },
  '+374': { country: 'Armenia', currency: 'AMD', symbol: '֏', locale: 'hy-AM', flag: '🇦🇲' },
  '+994': { country: 'Azerbaijan', currency: 'AZN', symbol: '₼', locale: 'az-AZ', flag: '🇦🇿' },
  '+880': { country: 'Bangladesh', currency: 'BDT', symbol: '৳', locale: 'bn-BD', flag: '🇧🇩' },
  '+975': { country: 'Bhutan', currency: 'BTN', symbol: 'Nu.', locale: 'dz-BT', flag: '🇧🇹' },
  '+673': { country: 'Brunei', currency: 'BND', symbol: 'B$', locale: 'ms-BN', flag: '🇧🇳' },
  '+855': { country: 'Cambodia', currency: 'KHR', symbol: '៛', locale: 'km-KH', flag: '🇰🇭' },
  '+86': { country: 'China', currency: 'CNY', symbol: '¥', locale: 'zh-CN', flag: '🇨🇳' },
  '+357': { country: 'Cyprus', currency: 'EUR', symbol: '€', locale: 'el-CY', flag: '🇨🇾' },
  '+995': { country: 'Georgia', currency: 'GEL', symbol: '₾', locale: 'ka-GE', flag: '🇬🇪' },
  '+91': { country: 'India', currency: 'INR', symbol: '₹', locale: 'hi-IN', flag: '🇮🇳' },
  '+62': { country: 'Indonesia', currency: 'IDR', symbol: 'Rp', locale: 'id-ID', flag: '🇮🇩' },
  '+98': { country: 'Iran', currency: 'IRR', symbol: '﷼', locale: 'fa-IR', flag: '🇮🇷' },
  '+964': { country: 'Iraq', currency: 'IQD', symbol: 'ع.د', locale: 'ar-IQ', flag: '🇮🇶' },
  '+81': { country: 'Japan', currency: 'JPY', symbol: '¥', locale: 'ja-JP', flag: '🇯🇵' },
  '+7': { country: 'Kazakhstan', currency: 'KZT', symbol: '₸', locale: 'kk-KZ', flag: '🇰🇿' },
  '+82': { country: 'South Korea', currency: 'KRW', symbol: '₩', locale: 'ko-KR', flag: '🇰🇷' },
  '+996': { country: 'Kyrgyzstan', currency: 'KGS', symbol: 'с', locale: 'ky-KG', flag: '🇰🇬' },
  '+856': { country: 'Laos', currency: 'LAK', symbol: '₭', locale: 'lo-LA', flag: '🇱🇦' },
  '+60': { country: 'Malaysia', currency: 'MYR', symbol: 'RM', locale: 'ms-MY', flag: '🇲🇾' },
  '+960': { country: 'Maldives', currency: 'MVR', symbol: 'Rf', locale: 'dv-MV', flag: '🇲🇻' },
  '+976': { country: 'Mongolia', currency: 'MNT', symbol: '₮', locale: 'mn-MN', flag: '🇲🇳' },
  '+95': { country: 'Myanmar', currency: 'MMK', symbol: 'K', locale: 'my-MM', flag: '🇲🇲' },
  '+977': { country: 'Nepal', currency: 'NPR', symbol: 'रू', locale: 'ne-NP', flag: '🇳🇵' },
  '+92': { country: 'Pakistan', currency: 'PKR', symbol: '₨', locale: 'ur-PK', flag: '🇵🇰' },
  '+63': { country: 'Philippines', currency: 'PHP', symbol: '₱', locale: 'fil-PH', flag: '🇵🇭' },  '+65': { country: 'Singapore', currency: 'SGD', symbol: 'S$', locale: 'en-SG', flag: '🇸🇬' },
  '+94': { country: 'Sri Lanka', currency: 'LKR', symbol: 'රු', locale: 'si-LK', flag: '🇱🇰' },
  '+886': { country: 'Taiwan', currency: 'TWD', symbol: 'NT$', locale: 'zh-TW', flag: '🇹🇼' },
  '+992': { country: 'Tajikistan', currency: 'TJS', symbol: 'ЅМ', locale: 'tg-TJ', flag: '🇹🇯' },
  '+66': { country: 'Thailand', currency: 'THB', symbol: '฿', locale: 'th-TH', flag: '🇹🇭' },
  '+90': { country: 'Turkey', currency: 'TRY', symbol: '₺', locale: 'tr-TR', flag: '🇹🇷' },
  '+993': { country: 'Turkmenistan', currency: 'TMT', symbol: 'T', locale: 'tk-TM', flag: '🇹🇲' },
  '+998': { country: 'Uzbekistan', currency: 'UZS', symbol: 'som', locale: 'uz-UZ', flag: '🇺🇿' },
  '+84': { country: 'Vietnam', currency: 'VND', symbol: '₫', locale: 'vi-VN', flag: '🇻🇳' },
   '+670': { country: 'East Timor', currency: 'USD', symbol: '$', locale: 'pt-TL', flag: '🇹🇱' },
  '+679': { country: 'Fiji', currency: 'FJD', symbol: 'FJ$', locale: 'en-FJ', flag: '🇫🇯' },
  '+686': { country: 'Kiribati', currency: 'AUD', symbol: '$', locale: 'en-KI', flag: '🇰🇮' },
  '+692': { country: 'Marshall Islands', currency: 'USD', symbol: '$', locale: 'en-MH', flag: '🇲🇭' },
  '+691': { country: 'Micronesia', currency: 'USD', symbol: '$', locale: 'en-FM', flag: '🇫🇲' },
  '+674': { country: 'Nauru', currency: 'AUD', symbol: '$', locale: 'en-NR', flag: '🇳🇷' },
  '+850': { country: 'North Korea', currency: 'KPW', symbol: '₩', locale: 'ko-KP', flag: '🇰🇵' },
  '+680': { country: 'Palau', currency: 'USD', symbol: '$', locale: 'en-PW', flag: '🇵🇼' },
  '+675': { country: 'Papua New Guinea', currency: 'PGK', symbol: 'K', locale: 'en-PG', flag: '🇵🇬' },
  '+685': { country: 'Samoa', currency: 'WST', symbol: 'WS$', locale: 'sm-WS', flag: '🇼🇸' },
  '+677': { country: 'Solomon Islands', currency: 'SBD', symbol: 'SI$', locale: 'en-SB', flag: '🇸🇧' },
  '+676': { country: 'Tonga', currency: 'TOP', symbol: 'T$', locale: 'to-TO', flag: '🇹🇴' },
  '+688': { country: 'Tuvalu', currency: 'AUD', symbol: '$', locale: 'en-TV', flag: '🇹🇻' },
  '+678': { country: 'Vanuatu', currency: 'VUV', symbol: 'VT', locale: 'bi-VU', flag: '🇻🇺' },
  
  // Australia & New Zealand
  '+61': { country: 'Australia', currency: 'AUD', symbol: 'A$', locale: 'en-AU', flag: '🇦🇺' },
  '+64': { country: 'New Zealand', currency: 'NZD', symbol: 'NZ$', locale: 'en-NZ', flag: '🇳🇿' },

  // Africa
  '+27': { country: 'South Africa', currency: 'ZAR', symbol: 'R', locale: 'en-ZA', flag: '🇿🇦' },
  '+234': { country: 'Nigeria', currency: 'NGN', symbol: '₦', locale: 'en-NG', flag: '🇳🇬' },
  '+254': { country: 'Kenya', currency: 'KES', symbol: 'KSh', locale: 'en-KE', flag: '🇰🇪' },
  '+251': { country: 'Ethiopia', currency: 'ETB', symbol: 'Br', locale: 'am-ET', flag: '🇪🇹' },
  '+244': { country: 'Angola', currency: 'AOA', symbol: 'Kz', locale: 'pt-AO', flag: '🇦🇴' },
  '+229': { country: 'Benin', currency: 'XOF', symbol: 'CFA', locale: 'fr-BJ', flag: '🇧🇯' },
  '+267': { country: 'Botswana', currency: 'BWP', symbol: 'P', locale: 'en-BW', flag: '🇧🇼' },
  '+226': { country: 'Burkina Faso', currency: 'XOF', symbol: 'CFA', locale: 'fr-BF', flag: '🇧🇫' },
  '+257': { country: 'Burundi', currency: 'BIF', symbol: 'FBu', locale: 'fr-BI', flag: '🇧🇮' },
  '+237': { country: 'Cameroon', currency: 'XAF', symbol: 'FCFA', locale: 'fr-CM', flag: '🇨🇲' },
  '+238': { country: 'Cape Verde', currency: 'CVE', symbol: '$', locale: 'pt-CV', flag: '🇨🇻' },
  '+236': { country: 'Central African Republic', currency: 'XAF', symbol: 'FCFA', locale: 'fr-CF', flag: '🇨🇫' },
  '+235': { country: 'Chad', currency: 'XAF', symbol: 'FCFA', locale: 'fr-TD', flag: '🇹🇩' },
  '+269': { country: 'Comoros', currency: 'KMF', symbol: 'CF', locale: 'ar-KM', flag: '🇰🇲' },
  '+242': { country: 'Congo', currency: 'XAF', symbol: 'FCFA', locale: 'fr-CG', flag: '🇨🇬' },
  '+243': { country: 'Democratic Republic of the Congo', currency: 'CDF', symbol: 'FC', locale: 'fr-CD', flag: '🇨🇩' },
  '+253': { country: 'Djibouti', currency: 'DJF', symbol: 'Fdj', locale: 'fr-DJ', flag: '🇩🇯' },
  '+240': { country: 'Equatorial Guinea', currency: 'XAF', symbol: 'FCFA', locale: 'es-GQ', flag: '🇬🇶' },
  '+291': { country: 'Eritrea', currency: 'ERN', symbol: 'Nfk', locale: 'ti-ER', flag: '🇪🇷' },
  '+268': { country: 'Eswatini', currency: 'SZL', symbol: 'E', locale: 'en-SZ', flag: '🇸🇿' },
  '+241': { country: 'Gabon', currency: 'XAF', symbol: 'FCFA', locale: 'fr-GA', flag: '🇬🇦' },
  '+220': { country: 'Gambia', currency: 'GMD', symbol: 'D', locale: 'en-GM', flag: '🇬🇲' },
  '+233': { country: 'Ghana', currency: 'GHS', symbol: '₵', locale: 'en-GH', flag: '🇬🇭' },
  '+224': { country: 'Guinea', currency: 'GNF', symbol: 'FG', locale: 'fr-GN', flag: '🇬🇳' },
  '+245': { country: 'Guinea-Bissau', currency: 'XOF', symbol: 'CFA', locale: 'pt-GW', flag: '🇬🇼' },
  '+225': { country: 'Ivory Coast', currency: 'XOF', symbol: 'CFA', locale: 'fr-CI', flag: '🇨🇮' },
  '+266': { country: 'Lesotho', currency: 'LSL', symbol: 'L', locale: 'en-LS', flag: '🇱🇸' },
  '+231': { country: 'Liberia', currency: 'LRD', symbol: '$', locale: 'en-LR', flag: '🇱🇷' },
  '+261': { country: 'Madagascar', currency: 'MGA', symbol: 'Ar', locale: 'fr-MG', flag: '🇲🇬' },
  '+265': { country: 'Malawi', currency: 'MWK', symbol: 'MK', locale: 'en-MW', flag: '🇲🇼' },
  '+223': { country: 'Mali', currency: 'XOF', symbol: 'CFA', locale: 'fr-ML', flag: '🇲🇱' },
  '+222': { country: 'Mauritania', currency: 'MRU', symbol: 'UM', locale: 'ar-MR', flag: '🇲🇷' },
  '+230': { country: 'Mauritius', currency: 'MUR', symbol: '₨', locale: 'en-MU', flag: '🇲🇺' },
  '+258': { country: 'Mozambique', currency: 'MZN', symbol: 'MT', locale: 'pt-MZ', flag: '🇲🇿' },
  '+264': { country: 'Namibia', currency: 'NAD', symbol: '$', locale: 'en-NA', flag: '🇳🇦' },
  '+227': { country: 'Niger', currency: 'XOF', symbol: 'CFA', locale: 'fr-NE', flag: '🇳🇪' },
  '+250': { country: 'Rwanda', currency: 'RWF', symbol: 'FRw', locale: 'rw-RW', flag: '🇷🇼' },
  '+239': { country: 'Sao Tome and Principe', currency: 'STN', symbol: 'Db', locale: 'pt-ST', flag: '🇸🇹' },
  '+221': { country: 'Senegal', currency: 'XOF', symbol: 'CFA', locale: 'fr-SN', flag: '🇸🇳' },
  '+248': { country: 'Seychelles', currency: 'SCR', symbol: '₨', locale: 'en-SC', flag: '🇸🇨' },
  '+232': { country: 'Sierra Leone', currency: 'SLL', symbol: 'Le', locale: 'en-SL', flag: '🇸🇱' },
  '+252': { country: 'Somalia', currency: 'SOS', symbol: 'Sh', locale: 'so-SO', flag: '🇸🇴' },
  '+211': { country: 'South Sudan', currency: 'SSP', symbol: '£', locale: 'en-SS', flag: '🇸🇸' },
  '+255': { country: 'Tanzania', currency: 'TZS', symbol: 'TSh', locale: 'sw-TZ', flag: '🇹🇿' },
  '+228': { country: 'Togo', currency: 'XOF', symbol: 'CFA', locale: 'fr-TG', flag: '🇹🇬' },
  '+256': { country: 'Uganda', currency: 'UGX', symbol: 'USh', locale: 'en-UG', flag: '🇺🇬' },
  '+260': { country: 'Zambia', currency: 'ZMW', symbol: 'ZK', locale: 'en-ZM', flag: '🇿🇲' },
  '+263': { country: 'Zimbabwe', currency: 'ZWL', symbol: '$', locale: 'en-ZW', flag: '🇿🇼' },

  // South America
  '+55': { country: 'Brazil', currency: 'BRL', symbol: 'R$', locale: 'pt-BR', flag: '🇧🇷' },
  '+54': { country: 'Argentina', currency: 'ARS', symbol: '$', locale: 'es-AR', flag: '🇦🇷' },
  '+57': { country: 'Colombia', currency: 'COP', symbol: '$', locale: 'es-CO', flag: '🇨🇴' },
  '+56': { country: 'Chile', currency: 'CLP', symbol: '$', locale: 'es-CL', flag: '🇨🇱' },
  '+51': { country: 'Peru', currency: 'PEN', symbol: 'S/', locale: 'es-PE', flag: '🇵🇪' },
  '+1268': { country: 'Antigua and Barbuda', currency: 'XCD', symbol: '$', locale: 'en-AG', flag: '🇦🇬' },
  '+1242': { country: 'Bahamas', currency: 'BSD', symbol: '$', locale: 'en-BS', flag: '🇧🇸' },
  '+1246': { country: 'Barbados', currency: 'BBD', symbol: '$', locale: 'en-BB', flag: '🇧🇧' },
  '+501': { country: 'Belize', currency: 'BZD', symbol: 'BZ$', locale: 'en-BZ', flag: '🇧🇿' },
  '+591': { country: 'Bolivia', currency: 'BOB', symbol: 'Bs.', locale: 'es-BO', flag: '🇧🇴' },
  '+506': { country: 'Costa Rica', currency: 'CRC', symbol: '₡', locale: 'es-CR', flag: '🇨🇷' },
  '+53': { country: 'Cuba', currency: 'CUP', symbol: '$', locale: 'es-CU', flag: '🇨🇺' },
  '+1767': { country: 'Dominica', currency: 'XCD', symbol: '$', locale: 'en-DM', flag: '🇩🇲' },
  '+1809': { country: 'Dominican Republic', currency: 'DOP', symbol: 'RD$', locale: 'es-DO', flag: '🇩🇴' },
  '+593': { country: 'Ecuador', currency: 'USD', symbol: '$', locale: 'es-EC', flag: '🇪🇨' },
  '+503': { country: 'El Salvador', currency: 'USD', symbol: '$', locale: 'es-SV', flag: '🇸🇻' },
  '+1473': { country: 'Grenada', currency: 'XCD', symbol: '$', locale: 'en-GD', flag: '🇬🇩' },
  '+502': { country: 'Guatemala', currency: 'GTQ', symbol: 'Q', locale: 'es-GT', flag: '🇬🇹' },
  '+592': { country: 'Guyana', currency: 'GYD', symbol: '$', locale: 'en-GY', flag: '🇬🇾' },
  '+509': { country: 'Haiti', currency: 'HTG', symbol: 'G', locale: 'ht-HT', flag: '🇭🇹' },
  '+504': { country: 'Honduras', currency: 'HNL', symbol: 'L', locale: 'es-HN', flag: '🇭🇳' },
  '+1876': { country: 'Jamaica', currency: 'JMD', symbol: '$', locale: 'en-JM', flag: '🇯🇲' },
  '+52': { country: 'Mexico', currency: 'MXN', symbol: '$', locale: 'es-MX', flag: '🇲🇽' },
  '+505': { country: 'Nicaragua', currency: 'NIO', symbol: 'C$', locale: 'es-NI', flag: '🇳🇮' },
  '+507': { country: 'Panama', currency: 'PAB', symbol: 'B/.', locale: 'es-PA', flag: '🇵🇦' },
  '+595': { country: 'Paraguay', currency: 'PYG', symbol: '₲', locale: 'es-PY', flag: '🇵🇾' },
  '+1869': { country: 'Saint Kitts and Nevis', currency: 'XCD', symbol: '$', locale: 'en-KN', flag: '🇰🇳' },
  '+1758': { country: 'Saint Lucia', currency: 'XCD', symbol: '$', locale: 'en-LC', flag: '🇱🇨' },
  '+1784': { country: 'Saint Vincent and the Grenadines', currency: 'XCD', symbol: '$', locale: 'en-VC', flag: '🇻🇨' },
  '+597': { country: 'Suriname', currency: 'SRD', symbol: '$', locale: 'nl-SR', flag: '🇸🇷' },
  '+1868': { country: 'Trinidad and Tobago', currency: 'TTD', symbol: 'TT$', locale: 'en-TT', flag: '🇹🇹' },
  '+598': { country: 'Uruguay', currency: 'UYU', symbol: '$U', locale: 'es-UY', flag: '🇺🇾' },
  '+58': { country: 'Venezuela', currency: 'VES', symbol: 'Bs.', locale: 'es-VE', flag: '🇻🇪' },
};

// Group countries by region for easier selection
export const REGIONS = {
  'Middle East': ['+971', '+966', '+974', '+973', '+968', '+965', '+961', '+963', '+962', '+967', '+970'],
  'North Africa': ['+20', '+218', '+216', '+213', '+212', '+249'],
  'Europe': ['+44', '+33', '+49', '+39', '+34', '+351', '+31', '+32', '+41', '+43', '+46', '+47', '+45', 
    '+358', '+353', '+48', '+380', '+40', '+30', '+36', '+420', '+421', '+386', '+385', '+381', '+359',
    '+355', '+376', '+375', '+387', '+372', '+354', '+371', '+423', '+370', '+352', '+356', '+373',
    '+377', '+382', '+389', '+378', '+379'],
  'North America': ['+1', '+1C', '+52'],
  'Central America': ['+501', '+502', '+503', '+504', '+505', '+506', '+507', '+509'],
  'Caribbean': ['+1242', '+1246', '+1268', '+1767', '+1809', '+1473', '+1876', '+1869', '+1758', '+1784', '+1868'],
  'South America': ['+55', '+54', '+57', '+56', '+51', '+591', '+593', '+595', '+597', '+598', '+58'],
  'Asia': ['+86', '+81', '+82', '+91', '+92', '+84', '+66', '+62', '+60', '+63', '+850'],
  'Pacific': ['+670', '+679', '+686', '+692', '+691', '+674', '+680', '+675', '+685', '+677', '+676', '+688', '+678'],
  'Africa': ['+27', '+234', '+254', '+251', '+244', '+229', '+267', '+226', '+257', '+237', '+238', '+236',
    '+235', '+269', '+242', '+243', '+253', '+240', '+291', '+268', '+241', '+220', '+233', '+224',
    '+245', '+225', '+266', '+231', '+261', '+265', '+223', '+222', '+230', '+258', '+264', '+227',
    '+250', '+239', '+221', '+248', '+232', '+252', '+211', '+255', '+228', '+256', '+260', '+263']
};

// Function to format phone numbers based on country code
export const formatPhoneNumber = (phoneNumber, countryCode) => {
  // Remove all non-numeric characters
  const cleaned = phoneNumber.replace(/\D/g, '');
  
  // Format based on country
  switch(countryCode) {
    case '+971': // UAE
      return cleaned.replace(/(\d{3})(\d{3})(\d{4})/, '$1 $2 $3');
    case '+966': // Saudi
      return cleaned.replace(/(\d{3})(\d{3})(\d{4})/, '$1 $2 $3');
    case '+20': // Egypt
      return cleaned.replace(/(\d{3})(\d{3})(\d{4})/, '$1 $2 $3');
    default:
      // Default international format
      return cleaned.replace(/(\d{3})(\d{3})(\d{4})/, '$1 $2 $3');
  }
};